passing bad syntax portion of grading script. Not sure about signal traps

diff --git a/stats b/stats
--- a/stats
+++ b/stats
@@ -14,6 +14,8 @@
 # now merged these into this single file.
 # -------------------------------------------------------------
 
+# exit on errors
+set -e;
 
 
 # global array variables
@@ -483,12 +485,14 @@ function checkInputs
 function main
 {
     filename=$(checkInputs $*);
-    # check if file exists
-    if [ -e $filename ]; then  # file exists
-	fileExists="true";# file exists so move on
+    # check if file exists and is readable
+    if [ -f $filename ]  && [ -r $filename  ] ; then  # file exists
+	# fileExists="true";# file exists so move on
 	calculateValues $*;
+	# echo $filename
     else 
-	printf "file '%s' not found\n" $filename;
+	# print error message to stderr, exit with value 1
+	echo "cannot read %s" $filename 1>&2;
 	exit 1;
     fi
     
